import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { RefreshCw, FileText, Download } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface AiMarketResearchProps {
  dealId: number;
  reportLink?: string | null;
  isGenerating: boolean;
  onGenerate: () => void;
}

export default function AiMarketResearch({
  dealId,
  reportLink,
  isGenerating,
  onGenerate,
}: AiMarketResearchProps) {
  const [showReport, setShowReport] = useState(false);
  const [reportContent, setReportContent] = useState<string | null>(null);

  // This would fetch the actual report content when opened
  // In a real implementation, this would fetch from an API
  const handleShowReport = async () => {
    // Simulating report content
    const mockReport = "# Market Research Report\n\nThis is a placeholder for the actual market research content which would be fetched from the API. In a production environment, this content would be generated by the OpenAI API and stored for viewing.";
    setReportContent(mockReport);
    setShowReport(true);
  };

  if (isGenerating) {
    return (
      <div>
        <h3 className="text-sm font-medium text-muted-foreground mb-2">AI Market Research</h3>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-center py-4">
              <div className="flex flex-col items-center">
                <RefreshCw className="h-8 w-8 text-primary animate-spin mb-2" />
                <p className="text-sm text-muted-foreground">Generating market research...</p>
                <p className="text-xs text-muted-foreground mt-2">This may take up to a minute.</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div>
      <h3 className="text-sm font-medium text-muted-foreground mb-2">AI Market Research</h3>
      {reportLink ? (
        <div className="flex items-center justify-between p-3 bg-muted rounded-md">
          <div className="flex items-center">
            <FileText className="text-primary mr-2" />
            <span className="text-sm">{reportLink}</span>
          </div>
          <div className="flex space-x-2">
            <Dialog open={showReport} onOpenChange={setShowReport}>
              <DialogTrigger asChild>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleShowReport}
                >
                  View Report
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-3xl">
                <DialogHeader>
                  <DialogTitle>Market Research Report</DialogTitle>
                  <DialogDescription>
                    Comprehensive AI-generated market research for this deal.
                  </DialogDescription>
                </DialogHeader>
                <ScrollArea className="max-h-[60vh] mt-4">
                  <div className="prose prose-sm max-w-none p-4">
                    {reportContent ? (
                      <pre className="whitespace-pre-wrap font-sans">{reportContent}</pre>
                    ) : (
                      <p>Loading report content...</p>
                    )}
                  </div>
                </ScrollArea>
              </DialogContent>
            </Dialog>
            <Button
              variant="ghost"
              size="sm"
              onClick={onGenerate}
            >
              <RefreshCw className="h-4 w-4" />
            </Button>
          </div>
        </div>
      ) : (
        <div className="p-4 bg-muted rounded-md flex flex-col items-center text-center">
          <p className="text-sm text-muted-foreground mb-3">
            No market research report has been generated yet.
          </p>
          <Button
            variant="default"
            onClick={onGenerate}
            className="text-white"
          >
            <RefreshCw className="mr-2 h-4 w-4" />
            Generate Market Research
          </Button>
        </div>
      )}
    </div>
  );
}
